#!/bin/bash
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    ln -s $(pwd)/.bashrc $HOME/.bashrc
    ln -s $(pwd)/.tmux.conf $HOME/.tmux.conf
    ln -s $(pwd)/.ideavimrc $HOME/.ideavimrc
    ln -s $(pwd)/.xinitrc $HOME/.xinitrc
    ln -sT $(pwd)/.vsnip $HOME/.vsnip
    ln -sT $(pwd)/.config/nvim $HOME/.config/nvim
    ln -sT $(pwd)/.config/alacritty $HOME/.config/alacritty
    ln -sT $(pwd)/.config/git $HOME/.config/git
    ln -sT $(pwd)/.config/dunst $HOME/.config/dunst
elif [[ "$OSTYPE" == "darwin"* ]]; then
    ln -s $(pwd)/.bashrc $HOME/.bashrc
    ln -s $(pwd)/.tmux.conf $HOME/.tmux.conf
    ln -s $(pwd)/.ideavimrc $HOME/.ideavimrc
    ln -sh $(pwd)/.vsnip $HOME/.vsnip
    ln -sh $(pwd)/.config/nvim $HOME/.config/nvim
    ln -sh $(pwd)/.config/alacritty $HOME/.config/alacritty
    ln -sh $(pwd)/.config/git $HOME/.config/git
fi

source $HOME/.bashrc
