#!/bin/bash
set -euxo pipefail
BACKEND=portaudio # mac
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  BACKEND=pulseaudio
fi
export BW_SESSION=$(bw unlock --raw)
spotifyd\
  -U 'bw get username spotify'\
  -P 'bw get password spotify'\
  --backend $BACKEND
spt
killall spotifyd
