#!/bin/bash
P=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    sudo dfu-util -D $P/assets/linux.bin
    source ~/.bashrc # reset xkbmap
elif [[ "$OSTYPE" == "darwin"* ]]; then
    sudo dfu-util -D $P/assets/mac.bin
fi
