#!/bin/bash
volume() {
    STATUS=$(amixer sget Master | tail -n1 | sed -r "s/.*\[(.*)\]/\1/")
    VOL=$(amixer get Master | tail -n1 | sed -r "s/.*\[(.*)%\].*/\1/")
    if [ "$STATUS" = "off" ]; then
        printf "VOL MUTE"
    else
        printf "VOL %s%%" "$VOL"
    fi
}

brightness() {
    BRI=$(printf "%.0f" "$(xbacklight)")
    printf "BRI %s%%" "$BRI"
}

battery() {
    ID=991051
    CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
    STATUS=$(cat /sys/class/power_supply/BAT0/status)
    if [[ $CAPACITY -lt 10 && "$STATUS" = "Discharging" ]]; then
        dunstify -i battery-level-10-symbolic -r $ID -u critical "Battery Low"
    else
        dunstify -C $ID
    fi
    printf "BAT %s%% %s" "$CAPACITY" "$STATUS"
}

xsetroot -name "$(volume) / $(brightness) / $(battery) / $(date +"%F %R")"
