#!/bin/bash
pactl -- set-sink-volume 0 +5%
SINK=$( pactl list short sinks | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' | head -n 1 )
NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )
notify-send "Volume Up" "$NOW" -i audio-volume-high-symbolic -t 300
